[package]
name = "web_app"
version = "0.1.0"
authors = ["Artem Sergeev <...>"]
edition = "2021"

[dependencies]
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
config = "0.15.7"
log = "0.4.25"
anyhow = "1.0.95"
